FlaxPDF
=======

FlaxPDF is a fast, nice multithreaded PDF viewer for the desktop.

As long as there are more pages than cores, every core will get a workout.

Light on dependencies, trimming borders, and aggressive caching are
its major points. Okular and Evince are nice but heavy; and the point
for starting this project, ePDFview, is dead.

EPDFview was nice and light, but lacking in a couple ways:

- no caching, if you wanted to backtrack one page, it reloaded slowly
- no automatic zoom to content/trim

Now with my main PDF viewer being dead, why not build a fresh one with
those two itches scratched?

Requirements
------------

Poppler, LZO, and FLTK 1.3.

Comparison
----------

Evince 3.10.3, FlaxPDF 0.6.1 and ePDFview 0.1.8 were tested. The same
document was scrolled repeatedly to check the cpu usage, the binary size
was measured, as well as RAM use.

		CPU		RAM		Binary
Evince		90%		56.8 MB		507 KB (evince + libpdfdocument.so)
ePDFView	72%		46.3 MB		124 KB
FlaxPDF		57% (5% *)	36.5 MB		45 KB

* To be fair to all, these measurements were done using the Vesa driver.
FlaxPDF, as the only one of the three, is able to take advantage of the GPU,
dropping its CPU use when scrolling to 5% (tested on radeon).

New capabilities added by Guy Turcotte (November 2016)
------------------------------------------------------

The following modifications have been made to allow FlaxPDF to be verstatile enough
to be used everyday as a pdf document viewer.

- Multi-columns document display
- Selection button for the last 10 viewed documents
- Automatically open the last viewed document
- Fullscreen mode
- PageUp and PageDown buttons
- Exit button 
- Scrollbars
- Gnome standard icons
